export default {
    LOAD_MATCHES_REQUEST : 'LOAD_MATCHES_REQUEST',
    LOAD_MATCHES_SUCCESS : 'LOAD_MATCHES_SUCCESS',
    LOAD_MATCHES_FAILED : 'LOAD_MATCHES_FAILED',
    LOAD_CURRENT_MATCH_SUCCESS: 'LOAD_CURRENT_MATCH_SUCCESS',
    ADD_MATCH_SUCCESS : 'ADD_MATCH_SUCCESS',
    ADD_MATCH_REQUEST : 'ADD_MATCH_REQUEST',
    ADD_MATCH_FAILED : 'ADD_MATCH_FAILED'
}