export default {
    LOAD_PLAN_REQUEST : 'LOAD_PLAN_REQUEST',
    LOAD_PLAN_SUCCESS : 'LOAD_PLAN_SUCCESS',
    LOAD_MIXES_SUCCESS : 'LOAD_MIXES_SUCCESS',
    LOAD_PLAN_FAILED : 'LOAD_PLAN_FAILED',
    LOAD_COMMENTS_SUCCESS : 'LOAD_COMMENT_SUCCESS',
    CLEAN_PLAN : 'CLEAN_PLAN',
    LOAD_LIKE_MOVIE : 'LOAD_LIKE_MOVIE',
    LOAD_CURRENT_MATCH_SUCCESS: 'LOAD_CURRENT_MATCH_SUCCESS',
    ADD_INVEST_SUCCESS : 'ADD_INVEST_SUCCESS',
    ADD_INVEST_REQUEST : 'ADD_INVEST_REQUEST',
    ADD_INVEST_FAILED : 'ADD_INVEST_FAILED'
}
