export default {
    LOAD_PLAN_REQUEST : 'LOAD_PLAN_REQUEST',
    LOAD_PLAN_SUCCESS : 'LOAD_PLAN_SUCCESS',
    LOAD_PLAN_FAILED : 'LOAD_PLAN_FAILED',
    LOAD_COMMENTS_SUCCESS : 'LOAD_COMMENT_SUCCESS',
    LOAD_LIKE_MOVIE : 'LOAD_LIKE_MOVIE',
    LOAD_CURRENT_MATCH_SUCCESS: 'LOAD_CURRENT_MATCH_SUCCESS',
    ADD_MATCH_SUCCESS : 'ADD_MATCH_SUCCESS',
    ADD_MATCH_REQUEST : 'ADD_MATCH_REQUEST',
    ADD_MATCH_FAILED : 'ADD_MATCH_FAILED'
}
